### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by yoshuawuyts** [karissa/dat-api#1]
I'm actually really liking this API - I feel it makes sense as it turns `dat` into a manager of multiple `hyperdrive` `archives` that are exposed over `hyperdiscovery`. Simple and to the point.

I think the only change I'd make would be to rename `dat.add` to `dat.create` / `dat.createRepo` as it's closer to the `hyperdrive` terminology of `drive.createArchive`.  - I'd use this repo :grin:

**Comment by yoshuawuyts** [comment]
Oh yeah, maybe one more thing: I wasn't sure why `repo.db` was defaulting to `memdb` - thought it might make more sense to use `level` by default instead?

**Comment by okdistribute** [comment]
Defaults to memdb for the easiest use case. Level has issues in the browser for larger datasets.

**Comment by okdistribute** [comment]
I'm torn between create and add, I don't think it really matters either way though so maybe it does make more sense to go with create since its more similar
