### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by pfrazee** [karissa/dat-api#11]
This repo is confusing some users! Could we explain in the readme why it's out of date, and archive it?

EDIT: rewrote to be less abrupt.

**Comment by yoshuawuyts** [comment]
@pfrazee yeah sounds good! - PR welcome; I can hit the "archive" button after a merge.

**Comment by joehand** [comment]
updated readme. will archive it.

**Comment by ahstro** [comment]
Sorry about the bump, but since the goal of this issue was to make users less confused, and I am very confused, would you mind clarifying why this was supposed to be archived and why it doesn't seem to have been? :innocent:

**Comment by okdistribute** [comment]
This repo is no longer out of date and is useful as nice defaults for hyperdrive in client side development
