### ISSUE TITLE
Info about dat-js

### ISSUE THREAD

**Issue by mydiscogr** [karissa/dat-api#12]
Hi I'm really interested in dat protocol, in particular I'm interested in dat-js, browser version.
I'd like to develop little app for the browser but:

- I can't find source of dat-js, althought I've found only minimized version
- I like to know if browser version cache file of others clients, like nodejs version:
I explain me better:
for example: I run 10 browser with simple data shared, the there're all online, well after a while one of this browser will shut down. 
Are data of the last client even available, even if only 3 or 4 of all have browsed content.
thanks

**Comment by joehand** [comment]
Hi there, I transferred this issue over to the dat-js repository. You can find an example of how to use hypercore (similarly with hyperdrive) in a browser here: https://github.com/joehand/hyperdb-web-example/tree/hypercore. 


- I can't find source of dat-js, althought I've found only minimized version

> See this repository.

- I like to know if browser version cache file of others clients, like nodejs version:
I explain me better:
for example: I run 10 browser with simple data shared, the there're all online, well after a while one of this browser will shut down. 
Are data of the last client even available, even if only 3 or 4 of all have browsed content.
thanks

> Yes, if they are shared via WebRTC (meaning the browser clients can connect directly)

**Comment by mydiscogr** [comment]
really thanks 👍

**Comment by okdistribute** [comment]
This is now up to date with the latest hyperdrive and works in the browser, feel free to open another issue if you're still having problems.
