### ISSUE TITLE
compare cache blob store to idb

### ISSUE THREAD

**Issue by okdistribute** [karissa/dat-api#14]
recently we started using the cache instead of indexeddb to store large images, the performance is much better https://github.com/digidem/cache-blob-store

wonder if we could create a `random-access-cache` (or if one exists) for that..

**Comment by joehand** [comment]
It'd also be fun to see how the file api works in chrome: https://github.com/random-access-storage/random-access-chrome-file

**Comment by RangerMauve** [comment]
This is addressed by #22 😀
