### ISSUE TITLE
`readFile` doesn't call the callback in some case

### ISSUE THREAD

**Issue by hossameldeen** [karissa/dat-api#20]
First of all: awesome work!

Second, the issue: `repo.archive.readFile` doesn't call the callback in some case.

### Reproduction

- Put the code below in an html file.
- Uncomment all comments (don't forget the comment at the end `//)}`).
- Open the file in the browser. You'll see the log correctly.
- Re-comment the code & open the file in the browser. **The problem: nothing gets logged**.

```html
<title>Check Chrome Console</title>
<script type="text/javascript" src="https://bundle.run/dat-js@7.1.0"></script>
<script type="text/javascript" src="https://bundle.run/random-access-idb@1.2.1"></script>

<script>
var Dat = datJs
/*var db = randomAccessIdb('dats')

var dat = new Dat()

var repo = dat.create({
  db: db
})

repo.archive.writeFile('/example.txt', 'Hello World!', () => {
  // Save it for later
  localStorage.setItem('My_Repo', repo.url)*/
  var db2 = randomAccessIdb('dats')
  var dat2 = new Dat()
  var repo2 = dat2.get(localStorage.getItem('My_Repo'), {
    db: db2
  })

  repo2.archive.readFile('/example.txt', 'utf-8', (err, data) => {
    console.log(`It's still there: ${data}`)
  })
//})
</script>
```

**Comment by RangerMauve** [comment]
The problem might be related to both instances of dat-js accessing the same storage instance at the same time. I'm not sure how random-access-idb is handling it under the hood, but it might be erroring out silently.

It should work if you close dat1 before initializing dat2.

```js
dat1.close(() => {
  var dat1 = new Dat()
  // etc here
})
```

Would you mind elaborating a bit on your usecase?

**Comment by hossameldeen** [comment]
I'm just trying out [the example in the README](https://github.com/datproject/dat-js#persisting-a-created-dat-and-loading-it-from-storage): writing a file and then reading it again in a second run.

I've tried what you said & still the same problem. After your suggestion & to clarify, I've split my code in 2 files. I first run `first-run.html` to write the file, then run `second-run.html` to read the file. `second-run.html` logs nothing (i.e., `readFile`'s callback is never called).

`first-run.html`:

```html
<title>Check Chrome Console</title>
<script type="text/javascript" src="https://bundle.run/dat-js@7.1.0"></script>
<script type="text/javascript" src="https://bundle.run/random-access-idb@1.2.1"></script>

<script>
var Dat = datJs
var db = randomAccessIdb('dats')

var dat = new Dat()

var repo = dat.create({
  db: db
})

repo.archive.writeFile('/example.txt', 'Hello World!', () => {
  // Save it for later
  localStorage.setItem('My_Repo', repo.url)
  repo.close(() => console.log('closed'))
})
</script>
```

`second-run.html`:

```html
<title>Check Chrome Console</title>
<script type="text/javascript" src="https://bundle.run/dat-js@7.1.0"></script>
<script type="text/javascript" src="https://bundle.run/random-access-idb@1.2.1"></script>

<script>
var Dat = datJs
var db = randomAccessIdb('dats')

var dat = new Dat()

var repo = dat.get(localStorage.getItem('My_Repo'), {
  db: db
})

repo.archive.readFile('/example.txt', 'utf-8', (err, data) => {
  console.log(`It's still there: ${data}`)
  dat.close(() => console.log('closed'))
})
</script>
```

Other info: I'm serving using npm `serve` package. (i.e., don't worry, not using `file:///` directly. Because I did initially xD).

Thank you for your time! :)

**Comment by RangerMauve** [comment]
Weird... it should be working. 😅

Try adding this around the code doing the reading:

```javascript
repo.ready(() => {
  repo.archive.readFile // etc.
})
```

**Comment by hossameldeen** [comment]
Tried but it didn't :cry:. `repo.ready()` callback is called but `readFile`'s is not.

I've made a reproduction repo [here](https://github.com/hossameldeen/dat-js-20-repro), if you have time to try it out. Does the issue reproduce at your side?

**Comment by hossameldeen** [comment]
A kind reminder. Does the issue reproduce at your side?

Note: Thank you for your efforts and I understand that you may have more urgent priorities at the moment and may not be able to get back to me promptly :)

**Comment by RangerMauve** [comment]
Sorry for not getting back to you! I haven't had a chance to look into it, but I've come across the problem before, though I think my issue was that I wasn't finding any peers.

I'm going to be doing dat-js stuff tomorrow so I'll add reproducing this to my TODO list!

You can also try out [random-access-web](https://github.com/RangerMauve/random-access-web) to see if that changes anything

**Comment by hossameldeen** [comment]
- No problem at all, nothing urgent is waiting :)) Thank you for adding it to your TODO list.

- Did as instructed but still same problem.

- This time, 2 new things happened:

  - Chrome asked for storing files permission (don't know if this is due to an update in chrome).

  - This warning was logged:

     ```
    VM56 dat-js@7.1.0:1 WebSocket connection to 
    'ws://signalhubws.mauve.moe/74fd6670ce6f50a91727b931' failed: WebSocket is closed before the 
    connection is established.
    ```

- Updated [reproduction repo](https://github.com/hossameldeen/dat-js-20-repro) with this change.

**Comment by ahstro** [comment]
Don't know if this is the same issue, but I'm having trouble using `repo.archive.readFile` at all. I've tried it on _the Dat project's URL_<sup>1</sup> and some others, but the callback is never called.

1) `dat://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330`

Edit: Here's the code I use, as requested on Gitter
```js
import Dat from "dat-js";

var dat = new Dat();
var repo = dat.get("dat://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330");
var readStream = repo.archive.readFile("/index.html", {}, function(err, data) {
  console.log("foo"); // never called
});
```

**Comment by RangerMauve** [comment]
ahstro: Have you tried putting your dat on hashbase?

**Comment by okdistribute** [comment]
This could be a race condition. 

Does it work if you wrap your code in `repo.ready(() =>...) `? That's what the tests do. It's possible that this got overlooked in the readme examples. If that works, and you have time to open a PR to fix the example, we would merge it!

**Comment by RangerMauve** [comment]
@karissa, that's what @hossameldeen tried and it didn't work for them. I'm checking out the repo now.

**Comment by RangerMauve** [comment]
It seems my signalhubws instance isn't working over HTTP. I might have messed up my nginx config

**Comment by ahstro** [comment]
@karissa I tried using `repo.ready`, didn't make a difference, but thanks for the suggestion.

@RangerMauve Yeah, just noticed `"Firefox can’t establish a connection to the server at ws://signalhubws.mauve.moe/2f0cc56a97d604540137ae6c."` in my console. Wasn't showing up before though, which is strange

**Comment by RangerMauve** [comment]
I think the WS error is popping up when the connection gets closed. with `repo.close()`.

I'm still not sure why it won't read. 😭

**Comment by RangerMauve** [comment]
It's like it isn't loading the data or something. :S

**Comment by ahstro** [comment]
Yeah, I dug into some of the libraries and `stream.on('data')` never seems to happen :confused:

**Comment by RangerMauve** [comment]
OMG! I found the bug. Thank you so much for creating the issue.

In @hossameldeen 's case, when we invoked `dat.get(url, opts)` the options weren't actually being passed into the repo. So when the archive was being created, the DB was used to save the data, but when we tried to get it after, the DB parameter was ignored.

A quick fix that can be done right away is to put the db parameter into the constructor of dat.

@ahstro I'm looking into the issue you're describing next. I think it's different from this initial problem. Are you using a local server to test your HTML file, or are you loading the file in your browser directly?

**Comment by RangerMauve** [comment]
@hossameldeen Version 7.1.1 works with your example repo!

**Comment by RangerMauve** [comment]
@ahstro The reason you're not getting any data is that `dat-js` doesn't have a gateway configured by default.

Try using this to initialize Dat:

```js
var dat = new Dat({
  gateway: 'ws://gateway.mauve.moe:3000'
})
```

**Comment by hossameldeen** [comment]
Thank you for fixing it! :-)

For the record, I can confirm that it's now working.
