### ISSUE TITLE
Question: Possible to interact with DAT protocol over HTTP?

### ISSUE THREAD

**Issue by eklem** [karissa/dat-api#21]
Is it possible to interact with something DAT in a webapp (some static files) over HTTP? Not just be shown a data replication, but actually interact, like one or several people updating a a hyperDB, living ini indexedDB.

The reason for the question is that not many people use Beaker Browser, and not many people will install a plugin for Firefox / Chrome. Kind of "How to get the future to everyone, now" 😄

**Comment by RangerMauve** [comment]
The biggest limitation right now is that browsers don't provide APIs that would allow us to register protocol handlers for Dat.

Firefox is the only one that supports `dat://` in their [registerProtocolHandler](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) implementation.

I'm currently working on [load-dat-page](https://github.com/RangerMauve/load-dat-page) which will be able to load dat content using dat-js, albeit really slowly. 😅
