### ISSUE TITLE
Does dat-js still create a Dat prototype on the window object?

### ISSUE THREAD

**Issue by DougAnderson444** [karissa/dat-api#25]
[The Dat website](https://docs.datproject.org/docs/browser-intro#install) says that you can just reference 
`<script type="text/javascript" src="https://bundle.run/dat-js@7"></script>`
and you get 
`a Dat prototype on the window object`
...is this still valid with the updates? Mind showing a gist of how to instantiate? It it something like 
`var dat = window.Dat()`? (Since I can't seem to get it to work :/) Thanks!

**Comment by RangerMauve** [comment]
I think it calls the global `DatJs` now

**Comment by RangerMauve** [comment]
Just checked the code and here's how you should be able to use it:

```html
<script type="text/javascript" src="https://bundle.run/dat-js@8"></script>
```

```js
const Dat = window.datJs

const dat = new Dat({
  // This flag will make it save the content locally to improve load speeds between refreshes
  persist: true
})
```

Note that I changed the version to `@8` since that adds a bunch of improvements.

**Comment by DougAnderson444** [comment]
Thanks, working with it now :)

For the persist flag, did you mean to put it here
```
const dat = new Dat()
var archive = dat.create({persist: true })
```
rather than here (?): 
```
const dat = new Dat({persist: true })
``` 

Or both?

I imagine there is a subtle difference between persisting the Dat() versus persisting the archive?

**Comment by RangerMauve** [comment]
Passing t into `Dat()` makes it so that _all_ archives persist. Passing it into `create()` or `get()` controls whether that specific archive will be persisted.
