### ISSUE TITLE
Using with Webpack

### ISSUE THREAD

**Issue by mkomod** [karissa/dat-api#28]
Hi, I'm getting the following error with dat-js 

Version: 8
```
 ERROR  Failed to compile with 1 errors                               8:14:59 PM

 error  in ./node_modules/@sammacbeth/random-access-idb-mutable-file/src/random-access-idb-mutable-file.js

Module parse failed: Unexpected token (4:12)
You may need an appropriate loader to handle this file type.
| 
| import RandomAccess from "random-access-storage"
> import type {
|   Stat,
|   Request,

 @ ./node_modules/random-access-web/index.js 38:24-77
 @ ./node_modules/dat-js/index.js
 @ ./src/boot/dat.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js
```

package.json

```{
  "name": "qdat",
  "version": "0.0.1",
  "scripts": {
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "dat-js": "^8.0.0",
    "quasar": "^1.0.0-beta.0"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.0-beta.0",
    "devtron": "1.4.0",
    "electron": "4.0.5",
    "electron-debug": "2.1.0",
    "electron-devtools-installer": "2.2.4",
    "strip-ansi": "=3.0.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0",
    "yarn": ">= 1.6.0"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ],
  "resolutions": {
    "ajv": "6.8.1"
  }
}
```

I don't get the same issue with dat-js v 7.1.1

**Comment by RangerMauve** [comment]
I usually build with [browserify](http://browserify.org/) and haven't come across this before. Could you double check that your webpack config supports the `browser` field from `package.json`?

**Comment by mkomod** [comment]
I've looked into configuring webpack, but did not manage to fix the issue.

I did however edit the package.json of ```/node_modules/@sammacbeth/random-access-idb-mutable-file```

from: ```"module": "src/random-access-idb-mutable-file",```
to: ```"module": "lib/random-access-idb-mutable-file",```

which did not result in any errors. however I'm unsure about how the functionality is effected

As of now the issue lies with random-access-idb and not dat-js. Is it worth opening an issue in that repo?

I'll keep messing about with webpack and see if I can get a cleaner fix

**Comment by RangerMauve** [comment]
Might be worth bothering the other repo. 😅

This is why I hate build tools sometimes. 🙃

**Comment by mkomod** [comment]
Thanks, for your help, I'll open up an issue.

**Comment by ozuchi** [comment]
Also encounter the same issue via `tsc` (non-webpack).

Bookmark the issue in other repo for progress tracking: https://github.com/Gozala/random-access-idb-mutable-file/issues/3

**Comment by RangerMauve** [comment]
@ozuchi You could try building dat-js with browserify into a UMD module and then importing it from there.

**Comment by DougAnderson444** [comment]
@RangerMauve and @karissa I am also getting this `@sammacbeth/random-access-idb-mutable-file` error with `webpack` and `babel`, can't quite seem to get around it with config. 

I am getting the `flow-node` error generated from the [babelrc](https://github.com/Gozala/random-access-idb-mutable-file/blob/4e449d33690729977dd184ccf9424c6ee5ef0299/.babelrc)
```
Error: Couldn't find preset "flow-node" relative to directory "node_modules/.registry.npmjs.org/@sammacbeth/random-access-idb-mutable-file/0.1.1/node_modules/@sammacbeth/random-access-idb-mutable-file"
```

I did notice a diff between [v 0.1.0](https://www.npmjs.com/package/random-access-idb-mutable-file) and [v0.1.1](https://www.npmjs.com/package/@sammacbeth/random-access-idb-mutable-file)... worthwhile making our own 0.1.2 that doesn't give errors? I don't know enough about babel, flow-node, or UMD to be useful on this one.

So, I ended up just using 
```
<script type="text/javascript" src="https://bundle.run/dat-js@8"></script>
``` 
instead to avoid the errors, but to the hacker in me it *feels wrong* but I need to forge through with my app instead of chasing this down...

**Comment by okdistribute** [comment]
cc @pvh how does one fix this? I don't know enough about browserify and webpack differences

**Comment by dpaez** [comment]
Hi all, I made a fix ([PR](https://github.com/Gozala/random-access-idb-mutable-file/pull/4)) to https://github.com/Gozala/random-access-idb-mutable-file/issues/3

Hopefully that can help us all.

**Comment by RangerMauve** [comment]
@dpaez That's awesome! Do you think you could submit a PR with an update to the dependency once it's merged? :D

**Comment by dpaez** [comment]
@RangerMauve of course!!! ;-)
