### ISSUE TITLE
npm docs & readme are sparse

### ISSUE THREAD

**Issue by tfolbrecht** [karissa/dat-api#34]
The dat-node package has a sample for dat creation and replication. It would be nice if this package had something similar.

**Comment by RangerMauve** [comment]
Hey!

The bottom of the README has a link to the [docs website](https://docs.datproject.org/docs/browser-intro) which has a bunch of examples.

Does that cover the use cases you have in mind? 😁

**Comment by tfolbrecht** [comment]
Oops, totally missed that, thank you!
