### ISSUE TITLE
Uncaught TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by DougAnderson444** [karissa/dat-api#36]
With dat-js@8.0.2, now when I go to do 
```
var archive = dat.create({
   persist: true
})
```
I get an uncaught TypeError:

![image](https://user-images.githubusercontent.com/6699901/62815847-a3859680-baec-11e9-9f92-aaa702b64f1f.png)

Code on [https://glitch.com/~dat-js-disco-penalty](https://glitch.com/~dat-js-disco-penalty)

**Comment by RangerMauve** [comment]
This is a problem with hyperdrive v9.16.0

Try installing hyperdrive@9.15 or switch to the Dat SDK. 😅

**Comment by DougAnderson444** [comment]
Yeah..as soon as I created this issue, I was like "crap, I meant to switch to sdk". But I was thinking the SDK isn't quite ready yet?

**Comment by RangerMauve** [comment]
Oh, the latest release is good to go, I think. :O
