### ISSUE TITLE
Is there any way to listen for changes

### ISSUE THREAD

**Issue by kkogovsek** [karissa/dat-api#37]
I looked through the documentation and I can't seem to find any information about how to listen to changes like you can with node.js API. Is that possible in the browser version as well?

**Comment by RangerMauve** [comment]
You should be able to listen for changes in the same way as the regular [hyperdrive API](https://github.com/mafintosh/hyperdrive/tree/e6741af1c9c2032ddef7db24596ad7268489d3dc#var-stream--archivehistoryoptions)
