### ISSUE TITLE
Is webrtc hub required?

### ISSUE THREAD

**Issue by nolotus** [karissa/dat-api#6]
var DEFAULT_SIGNALHUBS = 'https://signalhub.mafintosh.com'
?so need a server?

**Comment by yoshuawuyts** [comment]
Every network will need to have some form of bootstrapping for the initial discovery of nodes. Without it nodes wouldn't be able to find each other. In this case the signalhub server provides the bootstrapping. Does that make sense?

**Comment by joehand** [comment]
To add, anyone can use our server as your bootstrap server.

**Comment by nolotus** [comment]
so,  i know ,thank you , i want to build a complete Distributed  blog platform,,now, must use dat-node.
