### ISSUE TITLE
What's the alternative if it's "out of date"?

### ISSUE THREAD

**Issue by doraemondrian** [karissa/dat-api#9]
The first thing this repo says is it's out of date. Is this approach permanently discontinued? Or is there an alternative elsewhere I should look at?

Would love to start playing with Dat!

**Comment by millette** [comment]
Closest thing I found was mentionned in #5

**Comment by joehand** [comment]
Hey, sorry for the delayed response! Thanks @millette for the assist.

If you are looking to do stuff in the browser, you can use hyperdrive as #5 says via browserify or another module bundler. [See a bit more](https://docs.datproject.org/browser#under-the-hood) in our docs (under the hood section).

> Is this approach permanently discontinued?

It's not discontinued but we found WebRTC performance pretty lacking so we are focusing elsewhere for now.

We also have [dat-node](https://github.com/datproject/dat-node) if you aren't doing things in the browser.

**Comment by kaosat-dev** [comment]
Hi @joehand I am still a bit confused by the usage of hyperdrive : namely:
- can you use the dat `ids` directly in hyperdrive(without the dat:// protocol of course) ? 
- from my understanding of the docs, that would still suffer the same limitation as `dat-js` ie only being able to connect to other WebRTC based peers ?

**Comment by joehand** [comment]
>can you use the dat ids directly in hyperdrive(without the dat:// protocol of course) ?

Yes, the ids used in dat are the same as the hyperdrive id (`archive.key`).

> from my understanding of the docs, that would still suffer the same limitation as dat-js ie only being able to connect to other WebRTC based peers ?

Correct, that is one of the big reasons we moved away from it. You can use [electron-webrtc](https://github.com/mappum/electron-webrtc) to connect to webrtc clients in node.

**Comment by kaosat-dev** [comment]
thanks for the quick answers @joehand !
one last question if you do not mind based on
>Correct, that is one of the big reasons we moved away from it. You can use electron-webrtc to connect to webrtc clients in node.

This means there is currently no purely client side option to connect to the overall hyperdrive/ dat network at large ?

**Comment by joehand** [comment]
> This means there is currently no purely client side option to connect to the overall hyperdrive/ dat network at large ?

Correct (ish). Its a bit confusing.

There is not really a dat network "at large," it depends on how clients connect to each other - and you can only connect to clients that speak the same "language". Most of the tools (command line, desktop, beaker) use the same network protocols (tcp, udp, mdns) for discovery and data transfer so they can all co-exist. But none of those work in the browser =(.

To connect to other types of clients from the browser you need a proxy that can connect webrtc clients to tcp/udp clients. That's been in our TODO for awhile but it's harder to prioritize webrtc/browser for our use cases.

**Comment by carloslfu** [comment]
Hello @joehand, is there a list or a roadmap for that? If not, would be useful to have one. I want to contribute with this specific use case. Some thoughts on how to contribute would be appreciated.

**Comment by okdistribute** [comment]
This is now up to date with the latest hyperdrive and works in the browser, feel free to open another issue if you're still having problems.
